// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1OB3d87lbhM6P-Sqti_3DysAyVrOdkbY',
    appId: '1:703085851966:web:693792f475eb422213e86f',
    messagingSenderId: '703085851966',
    projectId: 'coderesq-d3af8',
    authDomain: 'coderesq-d3af8.firebaseapp.com',
    storageBucket: 'coderesq-d3af8.firebasestorage.app',
    measurementId: 'G-FV1BEGB9KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ixXEVyM7q8zmQlLyfYqxf9u3UnL9FJE',
    appId: '1:703085851966:android:b461f714931127c913e86f',
    messagingSenderId: '703085851966',
    projectId: 'coderesq-d3af8',
    storageBucket: 'coderesq-d3af8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjDvXz6d3yBQ3rExZZBPDkQ0dikRh2Ug',
    appId: '1:703085851966:ios:33e9cddaaa72741c13e86f',
    messagingSenderId: '703085851966',
    projectId: 'coderesq-d3af8',
    storageBucket: 'coderesq-d3af8.firebasestorage.app',
    iosBundleId: 'com.example.resqAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1OB3d87lbhM6P-Sqti_3DysAyVrOdkbY',
    appId: '1:703085851966:web:a82496b75b70fed213e86f',
    messagingSenderId: '703085851966',
    projectId: 'coderesq-d3af8',
    authDomain: 'coderesq-d3af8.firebaseapp.com',
    storageBucket: 'coderesq-d3af8.firebasestorage.app',
    measurementId: 'G-XVX1HJ2T9X',
  );
}
